version: '3.9'

services:
  stafl-devcontainer:
    image: "ghcr.io/staflsystems/stafl-devcontainer-ci:latest"
    environment:
      - KROKI_HOST=kroki
  kroki:
    image: yuzutech/kroki:latest
    ports:
      - 8000:8000



    