version: '3.9'

services:
  stafl-devcontainer:
    image: "ghcr.io/staflsystems/stafl-devcontainer-ci:latest"
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
      - data:/home/vscode
  kroki:
    image: ghcr.io/staflsystems/kroki:latest

volumes:
  data:
    name: stafl-devcontainer-data
